-- Create a new table
CREATE TABLE nyc_eviction_record (
  COURT_INDEX_NUMBER VARCHAR(20),
  DOCKET_NUMBER VARCHAR(15),
  EVICTION_ADDRESS VARCHAR(150),
  EVICTION_APT_NUM VARCHAR(20),
  EXECUTED_DATE VARCHAR(20),
  MARSHAL_FIRST_NAME VARCHAR(20),
  MARSHAL_LAST_NAME VARCHAR(20),
  RESIDENTIAL_COMMERCIAL_IND VARCHAR(30),
  BOROUGH VARCHAR(20),
  EVICTION_ZIP VARCHAR(20)	
);
